In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import sciviz

In [7]:
data = sciviz.load_data("cancer")
display(data)

,Sample,GROUP,Stage,Grade,Sex,AARSD1,ABL1,ACAA1,ACAN,ACE2,...,FCRL6,FCRLB,FEN1,FES,FETUB,FGF19,FGF2,FGF21,FGF23,FGF5
0,AML_syn_1,AML,2,NaN,Female,3.390346,2.758852,1.707009,0.033271,1.755359,...,0.788559,3.719864,3.024967,0.261721,-0.304457,2.874048,1.260914,1.005857,0.977870,0.341354
1,AML_syn_2,AML,Unknown,NaN,Male,1.422795,1.247305,-0.816163,-0.459183,0.826406,...,2.217510,2.175795,1.491146,-0.466368,0.727437,0.122274,-0.081686,1.276396,0.572879,-0.689004
2,AML_syn_3,AML,2,NaN,Female,NaN,NaN,NaN,0.989325,NaN,...,0.465197,NaN,NaN,NaN,0.578713,1.652374,2.985148,NaN,NaN,NaN
3,AML_syn_4,AML,Unknown,NaN,Male,3.409418,3.383503,1.692789,NaN,1.520753,...,1.513665,0.853929,0.271311,2.288791,0.391194,0.853167,3.745419,1.012613,0.645404,0.170451
4,AML_syn_5,AML,2,NaN,Female,5.011080,5.054630,0.127958,0.400505,-0.932535,...,1.729924,0.818500,2.783525,1.434795,1.184172,1.461130,2.637332,2.086817,-0.563559,-0.460146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,MYEL_syn_34,MYEL,NaN,NaN,Male,NaN,NaN,NaN,1.268105,NaN,...,-1.053987,NaN,NaN,NaN,-0.068604,1.221995,2.022401,NaN,NaN,NaN
332,MYEL_syn_35,MYEL,NaN,NaN,Male,4.948372,3.957622,1.771119,-0.569045,1.848514,...,1.966979,8.790835,2.826590,2.516012,-2.336564,1.186083,2.004810,1.156546,1.700665,0.375576
333,MYEL_syn_36,MYEL,NaN,NaN,Male,NaN,NaN,-0.900412,1.107953,1.457596,...,-1.601959,4.371718,0.241824,0.682449,0.330976,-0.531316,0.279925,0.518319,1.674718,0.947515
334,MYEL_syn_37,MYEL,NaN,NaN,Male,3.791249,2.536717,1.100585,1.203660,1.376443,...,0.292635,5.685956,0.617759,0.401273,0.443195,-0.180425,3.420306,2.469819,2.778480,1.942609
335,MYEL_syn_38,MYEL,NaN,NaN,Female,1.645268,4.130089,2.147295,1.655807,2.656187,...,2.041124,1.190578,-0.716628,0.843912,-1.545787,-0.663786,-0.117932,4.164678,5.845944,-0.105566